### ISSUE TITLE
the way to make the <i> hidden when there is no children of it

### ISSUE THREAD

**Issue by mizuka-wu** [hsiaosiyuan0/vue-tree#1]
add new function to i like this<i @click="autoExpand" v-if="isHaveChild(data.children)"></i> 
and a new option to data like this      haveChild:true
the function is that     

isHaveChild(child){
        return (!(child.length===0&&this.loader===EMPTY_FN))&&this.haveChild
    },

**Comment by hsiaosiyuan0** [comment]
PR is welcome :-p
