### ISSUE TITLE
IE11下 forEach没有编译为es5, 报错不支持此属性 。

### ISSUE THREAD

**Issue by WTBF** [hsiaosiyuan0/vue-tree#2]
![image](https://cloud.githubusercontent.com/assets/10608477/24843492/e6a7a310-1dd5-11e7-92c1-fbbd6bccb859.png)

**Comment by hsiaosiyuan0** [comment]
和是否编译成 es5 无关，是 IE 下 `NodeList` 没有 `forEach` 方法，不过这个 repo 很久没有维护了，并且支持 IE 的意义也不大，所以只有麻烦你在自己的 fork 里面修改啦
